seed: 42

image_size: [240, 320]

model:
  batch_size: 16 # 64
  eval_batch_size: 8 # 16

  detection_threshold: 0.001
  lambda_det: 1
  lambda_desc: 0
  dense_loss:
        enable: false
        params:
            descriptor_dist: 4 # 4, 7.5
            lambda_d: 800 # 800
  sparse_loss:
      enable: true
      params:
          num_matching_attempts: 1000
          num_masked_non_matches_per_match: 100
          lamda_d: 1
          dist: 'cos'
          method: '2d'
# Данные
data:
  synthetic_dataset: "datasets/data"
  dataset: "SyntheticDataset"  # имя модуля датасета
  image_size:  ${image_size} # размер синтетических изображений

# Подготовка синтетических данных
prepare_synthetic_dataset:
  seed: ${seed}
  train_size: 0.8
  data_dir: ${data.synthetic_dataset}
  blur_size: 21
  image_size: ${image_size}
  background_size: [960, 1280]
  model:
    batch_size: ${model.batch_size}
    eval_batch_size: ${model.eval_batch_size}

  aug:
    photometric:
        enable: true
        enable_train: true
        enable_val: false
    homographic:
      enable: true
      enable_train: true
      enable_val: false
      valid_border_margin: 2
  primitives: 
    draw_lines: 20000
    draw_polygon: 20000
    draw_multiple_polygons: 20000
    draw_ellipses: 20000
    draw_star: 20000
    draw_checkerboard: 20000
    draw_stripes: 20000
    draw_cube: 20000
    gaussian_noise: 20000

synth_dataset_gaussian:
  primitives: "all"
  truncate: {draw_ellipses: 0.3, draw_stripes: 0.2, gaussian_noise: 0.1}
  validation_size: -1
  test_size: -1
  "on-the-fly": False
  cache_in_memory: true  # Используем из data
  suffix: 'v6'  # Используем из data
  add_augmentation_to_test_set: False
  num_parallel_calls: 10
  preprocessing:
    resize: [120, 160]
    blur_size: 21
  augmentation:
    photometric:
      enable: true
      enable_train: true
      enable_val: false
    homographic:
      enable: true
      enable_train: true
      enable_val: false
  warp_input: true  

# Тренировка
training:
  seed: ${seed}
  workers_train: 0 # 4
  workers_val: 0   # 2
  learning_rate: 0.001
  

# Дополнительные параметры датасета (если нужны)
dataset_params:
  warp_input: true
  normalize: true

train_iter: 200000
front_end_model: "Train_model_frontend"