seed: 0xC00FFEE # seed для воспроизводимости

synthetic_dataset: data/synthetic_dataset # директория для синтетических изображений

prepare_synthetic_data:
  seed: ${seed}
  data_dir: ${synthetic_dataset}
  blur_size: 21
  image_size: [120, 160]
  primitives: 
    draw_lines: 20_000
    draw_polygon: 20_000
    draw_ellipses: 20_000
    draw_star: 20_000
    draw_checkerboard: 20_000
    draw_stripes: 20_000
    draw_cube: 20_000
    gaussian_noise: 20_000

train_magicpoint:
  seed: ${seed}
  data_dir: ${synthetic_dataset}
  train_size: 0.8
  batch_size: 128
  num_workers: 0
  augmentation:
    homographic:
      enable: true
      enable_train: true
      enable_val: false
      params:
        allow_artifacts: true
        max_angle: 1.57
        patch_ratio: 0.8
        perspective: true
        perspective_amplitude_x: 0.2
        perspective_amplitude_y: 0.2
        rotation: true
        scaling: true
        scaling_amplitude: 0.2
        translation: true
        translation_overflow: 0.05
      valid_border_margin: 2
    photometric:
      random_brightness:
        max_abs_change: 75
      random_contrast:
        strength_range: [0.3, 1.8]
      additive_gaussian_noise:
        stddev_range: [0, 15]
      additive_speckle_noise:
        prob_range: [0, 0.0035]
      motion_blur:
        max_kernel_size: 7
      additive_shade:
        kernel_size_range: [50, 100]
        transparency_range: [-0.5, 0.8]
        nb_ellipses: 20
        
        
        
