seed: 0xC00FFEE

synthetic_dataset: data/synthetic_dataset
image_size: [240, 320] # размер синтетических изображений

prepare_synthetic_dataset:
  seed: ${seed}
  data_dir: ${synthetic_dataset}
  blur_size: 21
  image_size: ${image_size}
  background_size: [960, 1280]
  primitives: 
    draw_lines: 20000
    draw_polygon: 20000
    draw_multiple_polygons: 20000
    draw_ellipses: 20000
    draw_star: 20000
    draw_checkerboard: 20000
    draw_stripes: 20000
    draw_cube: 20000
    gaussian_noise: 20000

train_magic_point:
  seed: ${seed}  
  test_size: 0.2
  data_dir: ${synthetic_dataset}
  batch_size: 64
  num_workers: 16
  train_aug:
    seed: ${seed}
