prepare_synthetic_data:
  seed: 0xC0FFEE
  data_dir: data/synthetic_dataset
  train_size: 0.8
  blur_size: 21
  background_size: [960, 1280]
  image_size: [120, 160]
  primitives:
    draw_lines: 20_000
    draw_polygon: 20_000
    draw_ellipses: 20_000
    draw_star: 20_000
    draw_checkerboard: 20_000
    draw_stripes: 20_000
    draw_cube: 20_000
    gaussian_noise: 20_000

train_magicpoint:
  seed: 0xC0FFEE
  num_epochs: 300 # 500
  learning_rate: 0.001
  cell_size: 8
  detection_threshold: 0.015
  nms_dist: 4
  limit_val_batches: 100
  log_dir: results/train_magic_point
  data_dir: data/synthetic_dataset
  train_size: 0.8
  train_batch_size: 64 # 128
  val_batch_size: 64
  num_workers: 12 # 16
  # число обновлений RichProgressBar в секунду
  refresh_rate: 1
  augmentation:
    homographic:
      allow_artifacts: true
      max_angle: 1.57
      patch_ratio: 0.8
      perspective: true
      perspective_amplitude_x: 0.2
      perspective_amplitude_y: 0.2
      rotation: true
      scaling: true
      scaling_amplitude: 0.2
      translation: true
      translation_overflow: 0.05
      n_scales: 5
      n_angles: 25
      valid_border_margin: 2

    photometric:
      random_brightness:
        max_abs_change: 75
      random_contrast:
        strength_range: [0.3, 1.8]
      additive_gaussian_noise:
        stddev_range: [0, 15]
      additive_speckle_noise:
        prob_range: [0, 0.0035]
      motion_blur:
        max_kernel_size: 7
      additive_shade:
        kernel_size_range: [50, 100]
        transparency_range: [-0.5, 0.8]
        nb_ellipses: 20

eval_magicpoint:
  data_dir: data/synthetic_dataset/test
  checkpoint: models/magic_point.ckpt # models/superpoint_v1.pth
  batch_size: 256
  output_dir: tmp
  detection_threshold: 0.015
  nms_dist: 4

download_satellite_data:
  data_dir: data/satellite
  max_workers: 12
  tiles_need: 10 # 625
  zoom: 17 # zoom 17 соответствует примерно 1 px / m
  num_tiles: 30 # 10 # число тайлов по ширине и высоте изображения
  tile_size: 256 # размер тайла в пикселях
  map_box:
    - 37.56000 # min_lon
    - 55.71500 # min_lat
    - 38.00000 # max_lon
    - 56.35000 # max_lat
  #osm: data/map.osm.pbf
  sources: ## TMS сервисы
    google: "http://mt1.google.com/vt/lyrs=s&x={x}&y={y}&z={z}"
    bing: "http://a0.ortho.tiles.virtualearth.net/tiles/a{}.jpeg?g=2"
    arcgis: "https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}"
    yandex: "https://sat04.maps.yandex.net/tiles?l=sat&x={x}&y={y}&z={z}"

prepare_satellite_images:
  seed: 0xC0FFEE
  satellite_dir: data/satellite
  # размер спутниковых изображений
  crop_size: 480
  images_dir: data/satellite_images
  train_size: 0.8

export_points:
  seed: 0xC0FFEE
  magic_point_model: models/magic_point.ckpt
  images_dir: data/satellite_images
  # размер спутниковых изображений
  crop_size: 480
  # размер ядра сглаживания изображений
  blur_size: 3
  # параметры детектирования ключевых точек
  detection_threshold: 0.001
  nms_dist: 4
  # batch size
  batch_size: 50
  # параметры аугментации
  augmentation:
    # минимальный и максимальный угол поворота в градусах
    min_angle: 0
    max_angle: 360
    # максимальный и минимальный сдвиг точек в аффинном преобразовании в процентах
    min_shift: -0.1
    max_shift: 0.1
    # диапазон изменения яркости в цветовой аугментации
    min_brightness: 0.7
    max_brightness: 1.3
    # диапазон изменения контрастности в цветовой аугментации
    min_contrast: 0.7
    max_contrast: 1.3
  # если debug_dir не null, в неё будут сохраняться отладочные изображения
  debug_dir: null

train_superpoint:
  seed: 0xC0FFEE
  num_epochs: 300 # 500
  learning_rate: 0.0001
  cell_size: 8
  detection_threshold: 0.015
  nms_dist: 4
  limit_val_batches: 100
  log_dir: results/train_super_point
  data_dir: data/home3/avsorokin_3/superpoint/data/satellite_images
  train_size: 0.8
  train_batch_size: 16 # 128
  val_batch_size: 16
  num_workers: 2 # 16
  # число обновлений RichProgressBar в секунду
  refresh_rate: 1
  lambda_loss: 1
  sparse_loss:
    num_matching_attempts: 1000
    num_masked_non_matches_per_match: 100
    lamda_d: 1
    dist: "cos"
    method: "2d"
  augmentation:
    crop_h: 320
    crop_w: 320
    # минимальный и максимальный угол поворота в градусах
    min_angle: 0
    max_angle: 360
    # максимальный и минимальный сдвиг точек в аффинном преобразовании в процентах
    min_shift: -0.1
    max_shift: 0.1
    # диапазон изменения яркости в цветовой аугментации
    min_brightness: 0.7
    max_brightness: 1.3
    # диапазон изменения контрастности в цветовой аугментации
    min_contrast: 0.7
    max_contrast: 1.3
    valid_border_margin: 2
    cell_size: 8
